import { type AnalysisResults } from "@shared/schema";

export function generatePDFReport(analysisResults: AnalysisResults): string {
  // For this implementation, we'll return a simple HTML that can be converted to PDF
  // In a production environment, you'd use a library like puppeteer or jsPDF
  const html = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>DropOffLens Analysis Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { color: #2563eb; margin: 0; }
        .summary { background: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
        .theme { margin-bottom: 30px; padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px; }
        .theme-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px; }
        .theme-name { font-size: 18px; font-weight: bold; color: #1f2937; }
        .theme-percentage { background: #2563eb; color: white; padding: 4px 12px; border-radius: 20px; font-size: 14px; }
        .quotes { background: #f9fafb; padding: 15px; border-left: 4px solid #d1d5db; margin: 15px 0; }
        .quote { font-style: italic; color: #6b7280; margin-bottom: 8px; }
        .action { background: #dbeafe; padding: 15px; border-radius: 8px; border-left: 4px solid #2563eb; }
        .footer { text-align: center; margin-top: 40px; color: #6b7280; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>DropOffLens Analysis Report</h1>
        <p>Customer Exit Feedback Analysis</p>
    </div>
    
    <div class="summary">
        <h2>Analysis Summary</h2>
        <p><strong>Total Feedback Entries:</strong> ${analysisResults.totalFeedback}</p>
        <p><strong>Key Themes Identified:</strong> ${analysisResults.themesFound}</p>
        <p><strong>Processing Time:</strong> ${analysisResults.processingTime.toFixed(2)} seconds</p>
        <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
    </div>
    
    ${analysisResults.themes.map((theme, index) => `
    <div class="theme">
        <div class="theme-header">
            <div class="theme-name">${index + 1}. ${theme.name}</div>
            <div class="theme-percentage">${theme.percentage}%</div>
        </div>
        
        <p><strong>Summary:</strong> ${theme.summary}</p>
        
        <div class="quotes">
            <strong>Representative Quotes:</strong>
            ${theme.quotes.map(quote => `<div class="quote">"${quote}"</div>`).join('')}
        </div>
        
        <div class="action">
            <strong>Suggested Action:</strong> ${theme.suggestedAction}
        </div>
    </div>
    `).join('')}
    
    <div class="footer">
        <p>Generated by DropOffLens - Powered by OpenAI GPT</p>
    </div>
</body>
</html>`;

  return html;
}
